name: CI/CD Local Sock Shop (carts)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  ci:
    name: Integracao Continua (Validacao)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Validar arquivos
        run: echo "Simulando testes e validacao de infraestrutura com sucesso!"

  cd_local:
    name: Entrega Continua (Deploy Local)
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Baixar imagem oficial do microservico carts
        run: docker pull weaveworksdemos/cart:latest

      - name: Parar container anterior (se existir)
        run: |
          docker stop sockshop-carts || true
          docker rm sockshop-carts || true

      - name: Subir container do microservico carts
        run: docker run -d --name sockshop-carts -p 8080:80 weaveworksdemos/cart:latest